# Generated by Django 6.0.4 on 2026-04-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_perfilusuario_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
    ]
